name: bonsai
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  grow:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
          
       - name: Pull latest changes
         run: |
           git pull --rebase origin main

       - uses: egorthinks/git-bonsai@v1 
      
